#pragma once
#define CONFIG_SECURE_SIGNED_APPS_NO_SECURE_BOOT 1
#define CONFIG_SECURE_SIGNED_ON_UPDATE_NO_SECURE_BOOT 1
#if defined(EOTA_TEST_CHIP_ID) && EOTA_TEST_CHIP_ID == 0
#define CONFIG_IDF_TARGET_ESP32 1
#define CONFIG_SECURE_SIGNED_APPS_ECDSA_SCHEME 1
#elif defined(EOTA_TEST_CHIP_ID) && EOTA_TEST_CHIP_ID == 5
#define CONFIG_IDF_TARGET_ESP32C3 1
#define CONFIG_SECURE_SIGNED_APPS_RSA_SCHEME 1
#elif defined(EOTA_TEST_CHIP_ID)
#error "Unsupported test chip ID"
#endif
#define CONFIG_MBEDTLS_CERTIFICATE_BUNDLE 1
#define CONFIG_MBEDTLS_HAVE_TIME_DATE 1
#define CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS 1
#define CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE 1
